"""Assemble the final audit package for a review (JSON and Markdown)."""
from datetime import datetime, timezone

from backend.db import Review

RISK_ORDER = {"high": 0, "medium": 1, "low": 2}
DISCLAIMER = (
    "Policy text is quoted verbatim from the cited section. Interpretations are generated by "
    "PolicyLens and are not policy. The final decision is made by the human reviewer."
)


def build(review: Review) -> dict:
    ev_by_id = {e.id: e for e in review.evidence}
    matrix, risks, questions = [], [], []
    for r in sorted(review.results, key=lambda x: (RISK_ORDER[x.requirement.risk], x.requirement.code)):
        req = r.requirement
        row = {
            "requirement": req.code,
            "citation": req.section.citation,
            "policy": req.section.policy.title,
            "policy_text": r.policy_quote,
            "risk": req.risk,
            "status": r.status,
            "interpretation": r.interpretation,
            "evidence": [f"E{i} {ev_by_id[i].filename}" for i in r.evidence_ids if i in ev_by_id],
            "decided_by": r.source,
            "confidence": r.confidence,
            "guardrail_notes": r.notes,
        }
        matrix.append(row)
        if r.status != "PASS":
            risks.append({"requirement": req.code, "citation": row["citation"], "risk": req.risk,
                          "status": r.status, "issue": r.interpretation})
            if r.status in ("UNKNOWN", "NEEDS_HUMAN_REVIEW"):
                questions.append(f"{req.code} ({row['citation']}): can you provide evidence that \"{req.text}\"?")

    decisions = [{"reviewer": d.reviewer, "action": d.action, "comment": d.comment, "at": d.created_at.isoformat()}
                 for d in review.decisions]
    high_open = [x for x in risks if x["risk"] == "high"]
    checklist = [
        {"item": "Every requirement has a status and a policy citation", "done": all(m["citation"] for m in matrix)},
        {"item": "No requirement is marked PASS without evidence", "done": all(m["evidence"] for m in matrix if m["status"] == "PASS")},
        {"item": "High-risk open items reviewed by a human", "done": not high_open or bool(decisions)},
        {"item": "Requested evidence provided", "done": not review.evidence_requested},
        {"item": "Decision recorded by a reviewer other than the submitter",
         "done": any(d["reviewer"] != review.submitted_by for d in decisions)},
    ]
    return {
        "review_id": review.id,
        "title": review.title,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "executive_summary": {
            "request": review.description,
            "submitted_by": review.submitted_by,
            "result": review.result,
            "status": review.status,
            "summary": review.summary,
            "final_decision": decisions[-1] if decisions else None,
        },
        "control_matrix": matrix,
        "evidence_references": [
            {"id": f"E{e.id}", "filename": e.filename, "type": e.evidence_type, "sha256": e.sha256,
             "uploaded_at": e.created_at.isoformat()} for e in review.evidence
        ],
        "open_questions": questions,
        "evidence_requested": review.evidence_requested,
        "risk_register": risks,
        "reviewer_checklist": checklist,
        "decision_history": decisions,
        "disclaimer": DISCLAIMER,
    }


def _cell(text) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def to_markdown(pkg: dict) -> str:
    es = pkg["executive_summary"]
    out = [
        f"# Audit Package: {pkg['title']} (review #{pkg['review_id']})",
        f"_Generated {pkg['generated_at']}_", "", f"> {pkg['disclaimer']}", "",
        "## Executive summary", "", f"**Request:** {es['request']}", "",
        f"**Submitted by:** {es['submitted_by']}  ", f"**Result:** {es['result']}  ", f"**Status:** {es['status']}", "",
        es["summary"] or "", "",
    ]
    if es["final_decision"]:
        d = es["final_decision"]
        out += [f"**Final decision:** {d['action']} by {d['reviewer']}: {d['comment']}", ""]
    out += ["## Control matrix", "", "| Requirement | Citation | Risk | Status | Policy text | Interpretation | Evidence |",
            "|---|---|---|---|---|---|---|"]
    for m in pkg["control_matrix"]:
        out.append("| " + " | ".join(_cell(x) for x in [m["requirement"], m["citation"], m["risk"], m["status"],
                                                           m["policy_text"], m["interpretation"], ", ".join(m["evidence"]) or "none"]) + " |")
    out += ["", "## Evidence references", ""]
    out += [f"- **{e['id']}** {e['filename']} ({e['type']}), sha256 `{e['sha256'][:16]}…`" for e in pkg["evidence_references"]] or ["- none"]
    out += ["", "## Open questions", ""] + ([f"- {q}" for q in pkg["open_questions"]] or ["- none"])
    out += ["", "## Evidence requested", ""] + ([f"- {e}" for e in pkg["evidence_requested"]] or ["- none"])
    out += ["", "## Risk register", "", "| Requirement | Citation | Risk | Status | Issue |", "|---|---|---|---|---|"]
    out += ["| " + " | ".join(_cell(x) for x in [r["requirement"], r["citation"], r["risk"], r["status"], r["issue"]]) + " |"
            for r in pkg["risk_register"]]
    out += ["", "## Reviewer checklist", ""] + [f"- [{'x' if c['done'] else ' '}] {c['item']}" for c in pkg["reviewer_checklist"]]
    out += ["", "## Decision history", ""] + ([f"- {d['at']}: **{d['action']}** by {d['reviewer']}: {d['comment']}"
                                               for d in pkg["decision_history"]] or ["- none"])
    return "\n".join(out) + "\n"
